{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "Location"
    },
    "host": "0.0.0.0:8080",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/locations": {
            "parameters": [
                {
                    "name": "page",
                    "in": "query",
                    "required": false,
                    "description": "Page of results to return",
                    "type": "integer"
                },
                {
                    "name": "per_page",
                    "in": "query",
                    "required": false,
                    "description": "Number of results to return per page",
                    "type": "integer"
                }
            ],
            "get": {
                "description": "Gets `Location` objects.\n",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Location"
                            }
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "id": "575c77445604c10007e9de0c",
                                    "latitude": 51.5354627689761,
                                    "longitude": -0.202750840374221,
                                    "altitude": 77.7268905639648,
                                    "horizontalAccuracy": 1844.97373451518,
                                    "verticalAccuracy": 10,
                                    "devicetime": "2016-06-11T21:40:30.915Z",
                                    "description": "location"
                                },
                                {
                                    "id": "575c76f65604c10007e9de0b",
                                    "latitude": 51.5548425469157,
                                    "longitude": -0.197759843647492,
                                    "horizontalAccuracy": 70.4187888570983,
                                    "deviceTime": "2016-06-11T21:33:21.862Z",
                                    "description": "visit"
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a `Location` object.\n",
                "parameters": [
                    {
                        "name": "pet",
                        "in": "body",
                        "description": "An array of Locations that you want to post",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Location"
                            }
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Location"
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "id": "575c77445604c10007e9de0c",
                                    "latitude": 51.5354627689761,
                                    "longitude": -0.202750840374221,
                                    "altitude": 77.7268905639648,
                                    "horizontalAccuracy": 1844.97373451518,
                                    "verticalAccuracy": 10,
                                    "devicetime": "2016-06-11T21:40:30.915Z",
                                    "description": "location"
                                },
                                {
                                    "id": "575c76f65604c10007e9de0b",
                                    "latitude": 51.5548425469157,
                                    "longitude": -0.197759843647492,
                                    "horizontalAccuracy": 70.4187888570983,
                                    "deviceTime": "2016-06-11T21:33:21.862Z",
                                    "description": "visit"
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/locations/{id}": {
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "description": "Location to fetch",
                    "type": "string"
                }
            ],
            "get": {
                "description": "Gets `Location` objects.\n",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Location"
                            }
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "id": "575c77445604c10007e9de0c",
                                    "latitude": 51.5354627689761,
                                    "longitude": -0.202750840374221,
                                    "altitude": 77.7268905639648,
                                    "horizontalAccuracy": 1844.97373451518,
                                    "verticalAccuracy": 10,
                                    "devicetime": "2016-06-11T21:40:30.915Z",
                                    "description": "location"
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Location": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number",
                    "format": "double"
                },
                "longitude": {
                    "type": "number",
                    "format": "double"
                },
                "altitude": {
                    "type": "number",
                    "format": "double"
                },
                "horizontalAccuracy": {
                    "type": "number",
                    "format": "double"
                },
                "verticalAccuracy": {
                    "type": "number",
                    "format": "double"
                },
                "deviceTime": {
                    "type": "string",
                    "format": "date-time"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "number",
                    "format": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}